name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
      CADDY_USER: ${{ secrets.CADDY_USER }}
      CADDY_PRIVATE_KEY: ${{ secrets.CADDY_PRIVATE_KEY }}
      NEXT_PUBLIC_FATHOM_ID: ${{ secrets.NEXT_PUBLIC_FATHOM_ID }} # Add this line

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.yarn
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        run: npm install -g yarn && yarn install

      - name: Build Project
        run: yarn build

      - name: Debug VPS Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            whoami
            ls -ld /var/www/html
            sudo -l -U ${{ secrets.VPS_USERNAME }}
          command_timeout: 1m

      - name: Clean VPS directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "" | sudo -S rm -rf /var/www/html/*
            echo "" | sudo -S mkdir -p /var/www/html
          command_timeout: 1m

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "out/"
          target: "/var/www/html"
          overwrite: true

      - name: Restart Caddy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.CADDY_USER }}
          key: ${{ secrets.CADDY_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "" | sudo -S /usr/bin/systemctl restart caddy
          command_timeout: 1m