name: Deploy site via Fleek
on: push
jobs:
  deploy-to-fleek:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.yarn
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Fleek CLI
        run: npm i -g @fleek-platform/cli
      - name: Install Packages
        run: npm install -g yarn && yarn install
      - name: Build & deploy sites
        run: fleek sites deploy
