name: Deploy to IPFS and Tor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.yarn
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Fleek CLI
      - name: Install Fleek CLI
        run: npm i -g @fleek-platform/cli

      # Install Packages
      - name: Install Packages
        run: npm install -g yarn && yarn install

      # Build the site
      - name: Build
        run: yarn build

      # Deploy to IPFS
      - name: Deploy to IPFS
        run: fleek sites deploy

      # Deploy to VPS via SCP
      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "out"
          target: "/var/www/html/out"

      # Restart Caddy on VPS
      - name: Restart Caddy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo systemctl restart caddy
          command_timeout: 5m